name: Git Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Validate commit messages
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            RANGE="origin/${{ github.event.pull_request.base.ref }}..HEAD"
          else
            RANGE="${{ github.event.before }}..HEAD"
          fi
          COMMITS=$(git log $RANGE --pretty=format:%s)
          if [ -z "$COMMITS" ]; then
            echo "No commits to lint"
          else
            echo "$COMMITS" | npx commitlint
          fi